# Development Environment Values Override
# These values will override the defaults in values.yaml when deployed to dev.

environment: "dev"
replicaCount: 1
container: 
  image:
    repository: "389642461016.dkr.ecr.us-east-1.amazonaws.com/docintel-dev-api"
    tag: "eb148f5"
    pullPolicy: "Always"
  secrets-provider-class: "docintel-dev-secrets-class"
  secrets-object: "docintel-dev-secrets"
  parameters-object: "docintel-dev-parameters"

gateway:
  name: "docintel-dev-api-gateway"
  namespace: "default"
  listenerName: "https"
env: 
  NODE_ENV: "dev"

keda:
  targetValue: 5
  window: 1m
  granularity: 10s
  minReplicaCount: 1
  maxReplicaCount: 5