# Production Environment Values Override
# These values will override the defaults in values.yaml when deployed to prod.

environment: "prod"
replicaCount: 5
container:
  image: ""
  tag: ""
  secrets-provider-class: ""
  secrets-object: ""
  parameters-object: ""