apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.projectName }}-{{ .Values.environment }}-{{ .Values.appName }}-sa
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": HookFailed
    {{ if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations }}
    {{ end }}