# Staging Environment Values Override
environment: "stg"
replicaCount: 2
container:
  image:
    repository: ""
    tag: "latest"
  secrets-provider-class: "docintel-stg-secrets-class"
  secrets-object: "docintel-stg-secrets"
  parameters-object: "docintel-stg-parameters"

env:
  PYTHON_ENV: "stg"

keda:
  minReplicaCount: 0
  maxReplicaCount: 5
  queueLength: "3"
