apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-helm-token
  namespace: argocd
spec:
  region: "${aws_region}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-ecr-helm-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  target:
    name: argocd-ecr-helm-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: helm
        name: ecr-helm-repo
        url: "${ecr_registry_url}/${project_name}/${environment}"
        enableOCI: "true"
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-helm-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-ecr-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  target:
    name: argocd-ecr-repo-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: helm
        url: "${ecr_registry_url}"
        enableOCI: "true"
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr-helm-token
