apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "${project_name}-${environment}-argocd-applicationset"
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: '${github_repository_url}'
        revision: '${targetRevision_api}'
        files:
          - path: "infra/k8s/argocd/${environment}/api/config.json"
    - git:
        repoURL: '${github_repository_url}'
        revision: '${targetRevision_worker}'
        files:
          - path: "infra/k8s/argocd/${environment}/worker/config.json"
  template:
    metadata:
      name: '${project_name}-${environment}-{{app}}'
      annotations:
        argocd.argoproj.io/sync-wave: "10" # Workloads deployed after core infrastructure
    spec:
      project: default
      source:
        repoURL: ${github_repository_url}
        targetRevision: '{{target_commit}}'
        path: '{{path}}'
        helm: 
          valueFiles:
          - values.yaml
          - values.${environment}.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
