# Staging Environment Values Override
environment: "stg"
replicaCount: 2
container:
  image:
    repository: ""
    tag: "latest"
  secrets-provider-class: "docintel-stg-secrets-class"
  secrets-object: "docintel-stg-secrets"
  parameters-object: "docintel-stg-parameters"

gateway:
  name: "docintel-stg-api-gateway"
  namespace: "default"
  listenerName: "https"

env:
  NODE_ENV: "stg"

keda:
  targetValue: 5
  window: 1m
  granularity: 10s
  minReplicaCount: 1
  maxReplicaCount: 5
