name: Worker CI/CD Workflow

on:
  push:
    branches:
      - dev
    paths:
      - 'apps/worker/**'
  pull_request:
    types: [closed]
    branches:
      - dev
    paths:
      - 'apps/worker/**'

permissions:
  id-token: write
  contents: write

jobs:
  deploy-worker:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/reusable-docker-helm-cicd.yml
    with:
      app_name: 'worker'
      app_path: './apps/worker'
      helm_values_path: 'infra/k8s/helm/worker/values.dev.yaml'
